-- ============================================================================================
-- 0003 — the read-only role behind text-to-SQL.
--
-- The Chat panel sends a question to an LLM, gets SQL back, and runs it. Everything about that
-- sentence is a reason to be careful: the statement is generated by a model from text a user typed,
-- and no amount of prompt engineering makes that trustworthy.
--
-- So there are two independent defences, and this file is the SECOND one — the one that holds when
-- the first fails:
--
--   1. `@weaver/textsql` parses the generated statement and refuses anything that is not a single
--      read. That is a string check, and string checks lose to inputs nobody thought of.
--   2. The connection it runs on CANNOT WRITE. Not "is not asked to" — cannot. A DELETE that gets
--      past the guard hits a role with no DELETE privilege and fails inside a read-only
--      transaction, twice over.
--
-- The role is created NOLOGIN and without a password on purpose: a password does not belong in a
-- file that is committed to a public repository. Give it one out of band, once, per environment:
--
--     alter role weaver_readonly with login password '<generated>';
--
-- Then point DATABASE_URL_READONLY at it. Until that is done, text-to-SQL reports that it is not
-- configured — it never silently falls back to the read-write connection, which is the failure mode
-- worth designing against here.
--
-- On Supabase, run this as `postgres`, which holds CREATEROLE. Through Supavisor the username then
-- takes the form `weaver_readonly.<project-ref>`.
-- ============================================================================================

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'weaver_readonly') then
    create role weaver_readonly nologin;
  end if;
end
$$;

-- Start from nothing rather than from whatever a previous run left. Re-running this migration must
-- converge on the same privileges, not accumulate them.
revoke all on schema public from weaver_readonly;
revoke all on all tables in schema public from weaver_readonly;
revoke all on all sequences in schema public from weaver_readonly;
revoke all on all functions in schema public from weaver_readonly;

grant usage on schema public to weaver_readonly;

-- ============================================================================================
-- SELECT on the six tables, named one by one.
--
-- Not `grant select on all tables in schema public`. The difference matters the day someone adds a
-- table: with an explicit list, a new table is invisible to text-to-SQL until a human grants it,
-- and the failure is "I cannot see that table" rather than an unreviewed disclosure. A security
-- boundary should fail towards showing less.
--
-- Deliberately NO `alter default privileges` for the same reason — that is the setting that would
-- auto-grant every future table.
-- ============================================================================================

grant select on table collectors       to weaver_readonly;
grant select on table golden_baselines to weaver_readonly;
grant select on table jobs             to weaver_readonly;
grant select on table runs             to weaver_readonly;
grant select on table healing_episodes to weaver_readonly;
grant select on table healing_attempts to weaver_readonly;

-- ============================================================================================
-- Session defaults. Belt and braces: the route sets these too, and a role that carries them cannot
-- have them forgotten by a caller.
-- ============================================================================================

-- Every transaction on this role starts read-only. A write does not merely lack a privilege — the
-- transaction itself refuses it, so an INSERT into a table the role somehow could write still fails.
alter role weaver_readonly set default_transaction_read_only = on;

-- Five seconds. A generated query is one a human is waiting for, and an unbounded cross join over
-- `runs` — 165 rows each carrying a full CLI payload — is exactly what a confused model produces.
alter role weaver_readonly set statement_timeout = '5s';

-- A transaction left open holds a connection out of a pool Supabase caps. Nothing here should ever
-- be idle in a transaction; ten seconds is generous.
alter role weaver_readonly set idle_in_transaction_session_timeout = '10s';

-- Pinned, so a schema created later cannot shadow `runs` with its own `runs` and change what a
-- reviewed query means.
alter role weaver_readonly set search_path = 'public';

comment on role weaver_readonly is
  'Text-to-SQL. SELECT on the six ledger tables, read-only transactions, 5s statement timeout. Never used by the worker or by any write path.';
